on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: ${{ github.run_number }}
        SLACK_TITLE	: "Report"
        SLACK_COLOR: ${{ job.status }}
        SLACK_MSG_AUTHOR: Test Automation Results
        SLACK_USERNAME: "Test"
  
  sending-email:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Send email
        uses: dawidd6/action-send-mail@v3.6.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.GMAIL_USERNAME}}
          password: ${{secrets.GMAIL_PASSWORD}}
          subject: Message from github actions.
          to: vinay08sharma@gmail.com
          from: Vinay Sharma
          secure: true
          body: workflow for ${{github.repository}} completed successfully!
     
